# Generated by Django 4.1.3 on 2023-01-02 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_top', models.PositiveSmallIntegerField(verbose_name='Location Top')),
                ('loc_right', models.PositiveSmallIntegerField(verbose_name='Location Right')),
                ('loc_bot', models.PositiveSmallIntegerField(verbose_name='Location Bottom')),
                ('loc_left', models.PositiveSmallIntegerField(verbose_name='Location Left')),
                ('encoding', models.BinaryField(verbose_name='Encoding')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered_in_cluster', models.BooleanField(default=False, verbose_name='Is registered in cluster')),
                ('central_face', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.faces', verbose_name='Central Face')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recognition.clusters', verbose_name='Cluster')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognition.people', verbose_name='Person')),
            ],
        ),
        migrations.AddField(
            model_name='faces',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.patterns', verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='faces',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.photos', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='clusters',
            name='center',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.patterns', verbose_name='Central Pattern'),
        ),
        migrations.AddField(
            model_name='clusters',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recognition.clusters', verbose_name='Parent'),
        ),
    ]
