# Generated by Django 4.1.3 on 2023-03-22 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_recalc_patt_del', models.PositiveSmallIntegerField(default=0, verbose_name='Not recalculated patterns deletions')),
            ],
            options={
                'verbose_name': 'Fractal Cluster of Patterns',
                'verbose_name_plural': 'Fractal Clusters of Patterns',
                'ordering': ['parent_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Index on photo')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['photo__slug', 'index'], unique=True, verbose_name='Face URL')),
                ('loc_top', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location Top')),
                ('loc_right', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location Right')),
                ('loc_bot', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location Bottom')),
                ('loc_left', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location Left')),
                ('encoding', models.BinaryField(blank=True, null=True, verbose_name='Encoding')),
            ],
            options={
                'verbose_name': 'Recognized Face',
                'verbose_name_plural': 'Recognized Faces',
                'ordering': ['photo', 'index'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Face URL')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recognized Person',
                'verbose_name_plural': 'Recognized People',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered_in_cluster', models.BooleanField(default=False, verbose_name='Is registered in cluster')),
                ('central_face', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.faces', verbose_name='Central Face')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recognition.clusters', verbose_name='Cluster')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognition.people', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Face Pattern',
                'verbose_name_plural': 'Faces Patterns',
                'ordering': ['person', 'central_face'],
            },
        ),
        migrations.AddField(
            model_name='faces',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognition.patterns', verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='faces',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.photos', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='clusters',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.patterns', verbose_name='Central Pattern'),
        ),
        migrations.AddField(
            model_name='clusters',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recognition.clusters', verbose_name='Parent'),
        ),
    ]
