# Generated by Django 4.1.3 on 2023-01-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faces',
            options={'ordering': ['photo', 'index']},
        ),
        migrations.AddField(
            model_name='faces',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Index on photo'),
        ),
        migrations.AlterField(
            model_name='faces',
            name='encoding',
            field=models.BinaryField(blank=True, null=True, verbose_name='Encoding'),
        ),
        migrations.AlterField(
            model_name='faces',
            name='loc_bot',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location Bottom'),
        ),
        migrations.AlterField(
            model_name='faces',
            name='loc_left',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location Left'),
        ),
        migrations.AlterField(
            model_name='faces',
            name='loc_right',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location Right'),
        ),
        migrations.AlterField(
            model_name='faces',
            name='loc_top',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Location Top'),
        ),
    ]
