# Generated by Django 4.1.3 on 2023-02-05 13:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_alter_faces_options_faces_index_alter_faces_encoding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='not_recalc_patt_del',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Not recalculated patterns deletions'),
        ),
        migrations.AddField(
            model_name='faces',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['photo__slug', 'index'], verbose_name='Face URL'),
        ),
        migrations.AlterField(
            model_name='clusters',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.patterns', verbose_name='Central Pattern'),
        ),
    ]
