# Generated by Django 4.1.3 on 2023-02-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_clusters_not_recalc_patt_del_faces_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognition.patterns', verbose_name='Pattern'),
        ),
    ]
