# Generated by Django 4.1.3 on 2023-02-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_alter_faces_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
