# Generated by Django 4.1.3 on 2023-02-22 16:17

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_alter_people_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True, verbose_name='Face URL'),
        ),
        migrations.AlterField(
            model_name='faces',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['photo__slug', 'index'], unique=True, verbose_name='Face URL'),
        ),
    ]
