# Generated by Django 4.1.3 on 2023-02-22 16:58

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0006_people_slug_alter_faces_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Face URL'),
        ),
    ]
