# Generated by Django 4.1.3 on 2023-02-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_alter_people_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusters',
            options={'verbose_name': 'Fractal Cluster of Patterns', 'verbose_name_plural': 'Fractal Clusters of Patterns'},
        ),
        migrations.AlterModelOptions(
            name='faces',
            options={'ordering': ['photo', 'index'], 'verbose_name': 'Recognized Face', 'verbose_name_plural': 'Recognized Faces'},
        ),
        migrations.AlterModelOptions(
            name='patterns',
            options={'ordering': ['person', 'central_face'], 'verbose_name': 'Face Pattern', 'verbose_name_plural': 'Faces Patterns'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['owner', 'name'], 'verbose_name': 'Recognized Person', 'verbose_name_plural': 'Recognized People'},
        ),
    ]
