version: "3"

services:
  django:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/familie_albums
    ports:
      - "8000:8000"
      - "587:587"
    environment:
      - DEBAG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
  celery:
    build: .
    container_name: celery
    command: celery -A photoalbums worker -l INFO
    volumes:
      - .:/usr/src/familie_albums
    depends_on:
      - django
      - redis
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    restart: always
    volumes:
      - ./mysql_db:/var/lib/mysql
  redis:
    container_name: redis
    image: "redis:alpine"
