# Generated by Django 4.1.3 on 2023-06-03 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='in_users_favorites',
            field=models.ManyToManyField(blank=True, related_name='albums_in_users_favorites', to=settings.AUTH_USER_MODEL, verbose_name="In Users' Favorites"),
        ),
        migrations.AlterField(
            model_name='albums',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='in_users_favorites',
            field=models.ManyToManyField(blank=True, related_name='photos_in_users_favorites', to=settings.AUTH_USER_MODEL, verbose_name="In Users' Favorites"),
        ),
    ]
