# Generated by Django 4.1.3 on 2023-01-20 11:03

from django.db import migrations
import mainapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_photos_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=mainapp.utils.TruncatingCharField(max_length=127, verbose_name='Title'),
        ),
    ]
