# Generated by Django 4.1.3 on 2023-01-20 11:49

from django.db import migrations, models
import mainapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_photos_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='original',
            field=models.ImageField(upload_to=mainapp.utils.get_photo_save_path, verbose_name='Original'),
        ),
    ]
