# Generated by Django 4.1.3 on 2023-02-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_photos_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
