# Generated by Django 4.1.3 on 2023-02-28 07:58

import accounts.utils
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=90, scale=1.0, size=[600, 600], upload_to=accounts.utils.get_avatar_save_path, verbose_name='Avatar'),
        ),
    ]
